export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  ACCOUNTING_FIRM_ADMIN = 'ACCOUNTING_FIRM_ADMIN',
  ACCOUNTANT = 'ACCOUNTANT',
  COMPANY_USER = 'COMPANY_USER',
}

export enum TenantType {
  PLATFORM = 'PLATFORM',
  ACCOUNTING_FIRM = 'ACCOUNTING_FIRM',
  COMPANY = 'COMPANY',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ReviewStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ExtractionStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_ERRORS = 'COMPLETED_WITH_ERRORS',
  FAILED = 'FAILED',
}

export enum FileType {
  INVOICE = 'INVOICE',
  PAYMENT = 'PAYMENT',
  BANK_STATEMENT = 'BANK_STATEMENT',
  SALARY_REGISTER = 'SALARY_REGISTER',
  LEDGER = 'LEDGER',
  MIS_REPORT = 'MIS_REPORT',
}

export enum BusinessType {
  MANUFACTURING = 'MANUFACTURING',
  IT_SERVICES = 'IT_SERVICES',
  CONSULTING = 'CONSULTING',
  RETAIL = 'RETAIL',
}

export enum AuditAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
}

export enum NotificationType {
  REVIEW_ASSIGNED = 'REVIEW_ASSIGNED',
  REVIEW_APPROVED = 'REVIEW_APPROVED',
  REVIEW_REJECTED = 'REVIEW_REJECTED',
  EXTRACTION_COMPLETED = 'EXTRACTION_COMPLETED',
  EXTRACTION_FAILED = 'EXTRACTION_FAILED',
  REVIEW_ESCALATED = 'REVIEW_ESCALATED',
  INVITE_SENT = 'INVITE_SENT',
}
